Add wait until ready function
DagsHub/streaming-client pull request #38
Opened 2023-07-20 11:48 UTC by idonov8

Pretty self explanatory, adding now to be used in the context of the Label Studio snippet

2023-07-20 11:58 UTC, kbolashev requested changes

2023-07-20 11:58 UTC, kbolashev commented on dagshub/data_engine/model/datasource.py
> +       """
I'm not sure if having this thing indefinite by default is normal. I think we should set it to something substantial enough that a reasonable sized repo could be scanned.
10 minutes or so maybe

If the processing gets stuck at any point you don't want the users to just be stuck forever

2023-07-20 11:58 UTC, kbolashev commented on dagshub/data_engine/model/datasource.py
> +                return
Raise an error here that the timeout has been exceeded

2023-07-20 11:58 UTC, kbolashev commented on dagshub/data_engine/model/datasource.py
> +        logger.info("Waiting for datasource preprocessing to complete")
logger.info() is not seen by default.
Check out this: https://rich.readthedocs.io/en/stable/reference/status.html if you want something nicer (don't forget to use the `rich_console` from the common imports so it's not displayed in quiet mode)

2023-07-20 11:58 UTC, kbolashev commented on dagshub/data_engine/model/datasource.py
> +       """
Ask Simon what he thinks a reasonable default timeout would be

2023-07-20 14:14 UTC, idonov8 commented
Added a call to wake up the LS workspace using the a endpoint (https://github.com/DagsHub/gogs/pull/1463) to save the user some time later in the flow.

2023-07-20 14:33 UTC, kbolashev requested changes
A bit more changes

2023-07-20 14:33 UTC, kbolashev commented on dagshub/data_engine/model/datasource.py
> +            time.sleep(1)
The spinner is a context manager so you can do
```python
with spinner:
    do_stuff
<will stop here automatically>
```

2023-07-20 14:33 UTC, kbolashev commented on dagshub/data_engine/model/datasource.py
> +
How does this request work on the backend? Does it wait for the workspace to spin up, or returns immediately?
If it's synchronous then it's a bad idea to wait for it to complete.
Also this doesn't handle any exceptions that could occur (not talking about non-200's, but more server timeouts), so maybe wrap it in a try/catch so it doesn't block the scan accidentally

2023-07-20 14:37 UTC, idonov8 commented on dagshub/data_engine/model/datasource.py
> +            time.sleep(1)
Cool!

2023-07-20 14:41 UTC, idonov8 commented on dagshub/data_engine/model/datasource.py
> +
Should return immediately, but maybe wait for https://github.com/DagsHub/gogs/pull/1463 to be approved to be sure

2023-07-23 10:06 UTC, kbolashev approved these changes

2023-07-23 10:06 UTC, merged